WIDTH = 800
HEIGHT = 720
FRAMERATE = 60
LOOT_TEXTURE_FOLDER = "assets/sprites/loot/"
MIN_LOOT_PER_ROOM = 5
MAX_LOOT_PER_ROOM = 5
COIN_PICKUP_SOUND = "assets/sounds/loot/item_pickup.wav"


# Might not get used in the final version, I just wanted to be able to hear my music when testing lmao
VOL_SFX = 0.1
VOL_MUSIC = 0.1


# World gen settings
WR_WIDTH = 200
SCALE = WIDTH/WR_WIDTH
WR_HEIGHT = round(WR_WIDTH * (HEIGHT / WIDTH))
WR_TILE_COUNT = 8
WR_TILE_HEIGHT = 100
ENEMY_MELEE_COOLDOWN = 30
ENEMY_RANGED_COOLDOWN = 100
ENEMY_SUMMONER_COOLDOWN = 50
ENEMY_SUMMONER_ANGLE_CHANGE = 0.01
ENEMY_SUMMONER_CIRCLE_RADIUS = 50

#Player settings
PLAYER_SPEED = 1
PLAYER_ATTACK_COOLDOWN = 30

#Enemy settings
ENEMY_DEFAULT_SPEED = 1
MELEE_ENEMY_ATTACK_SOUND = "assets/sounds/entities/enemies/melee/melee_attack_hit.ogg"
INERTIA_RANGE_MIN = 0.01
INERTIA_RANGE_MAX = 0.05

LIGHTNING_INERTIA_RANGE_MIN = 0.1
LIGHTNING_INERTIA_RANGE_MAX = 0.2

LOOT_SIZE_SMALL = (8,8)
LOOT_SIZE_MEDIUM = (16,16)
LOOT_SIZE_LARGE = (10,10)


# Scoreboard settings
SB_BACKGROUND_COLOR = (0,0,0,127)
HD_BACKGROUND_COLOR = (255,64,0,48)
CT_BACKGROUND_COLOR = (0,192,255,40)

SB_BORDER_COLOR = (255,255,255,255)
HD_BORDER_COLOR = (255,128,0,255)
CT_BORDER_COLOR = (0,192,255,255)

SB_TEXT_COLOR = (255,255,255)
HD_TEXT_COLOR = SB_TEXT_COLOR
CT_TEXT_COLOR = SB_TEXT_COLOR
